services:
  - type: web
    name: shift-help-notify-app
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_KEY
        generateValue: true
      - key: VAPID_CONTACT_EMAIL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
